/**
 * TypeScript Type Generation Script
 * 
 * Generates TypeScript types from the backend OpenAPI schema.
 * Run: npm run generate:types
 */

import { generate } from 'openapi-typescript-codegen';
import * as fs from 'fs';
import * as path from 'path';

const OPENAPI_SCHEMA_URL = process.env.OPENAPI_SCHEMA_URL || 'http://localhost:8000/openapi.json';
const OUTPUT_DIR = './types/generated';

async function generateTypes() {
  console.log('🔄 Starting TypeScript type generation...');
  console.log(`📥 Fetching OpenAPI schema from: ${OPENAPI_SCHEMA_URL}`);

  try {
    // Ensure output directory exists
    if (!fs.existsSync(OUTPUT_DIR)) {
      fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }

    // Generate types using openapi-typescript-codegen
    await generate({
      input: OPENAPI_SCHEMA_URL,
      output: OUTPUT_DIR,
      httpClient: 'fetch',
      useOptions: true,
      useUnionTypes: true,
      exportCore: true,
      exportServices: true,
      exportModels: true,
      exportSchemas: false,
    });

    console.log('✅ TypeScript types generated successfully!');
    console.log(`📁 Output directory: ${OUTPUT_DIR}`);

    // Generate a custom index file with additional exports
    generateIndexFile();

  } catch (error) {
    console.error('❌ Type generation failed:', error);
    
    // If network fetch fails, try to use local fallback
    console.log('💡 Tip: Make sure the backend server is running at', OPENAPI_SCHEMA_URL);
    console.log('   Or provide a local openapi.json file');
    
    // Generate placeholder types if generation fails
    generatePlaceholderTypes();
  }
}

function generateIndexFile() {
  const indexContent = `/**
 * Auto-generated TypeScript Types
 * 
 * Generated at: ${new Date().toISOString()}
 * Source: ${OPENAPI_SCHEMA_URL}
 * 
 * ⚠️ WARNING: Do not edit this file manually
 * Run \`npm run generate:types\` to regenerate
 */

// Re-export all generated types
export * from './models';
export * from './services';
export * from './core/ApiError';
export * from './core/ApiRequestOptions';
export * from './core/ApiResult';
`;

  fs.writeFileSync(
    path.join(OUTPUT_DIR, 'index.ts'),
    indexContent,
    'utf-8'
  );

  console.log('📝 Generated index file: types/generated/index.ts');
}

function generatePlaceholderTypes() {
  console.log('📝 Generating placeholder types...');

  // Create output directory
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Create models directory
  const modelsDir = path.join(OUTPUT_DIR, 'models');
  if (!fs.existsSync(modelsDir)) {
    fs.mkdirSync(modelsDir, { recursive: true });
  }

  // Write placeholder types based on backend models
  const placeholderTypes = `/**
 * Placeholder Types - Generated when backend is unavailable
 * 
 * These types match the backend Pydantic models in domain.py
 * Run \`npm run generate:types\` with the backend running to get full types
 */

// ============================================================
// User Input Models
// ============================================================

export interface LearningPreferences {
  learning_goal: string;
  available_hours_per_week: number;
  motivation: string;
  current_level: 'beginner' | 'intermediate' | 'advanced';
  career_background: string;
  content_preference: Array<'video' | 'text' | 'interactive' | 'project'>;
  target_deadline?: string | null;
}

export interface UserRequest {
  user_id: string;
  session_id: string;
  preferences: LearningPreferences;
  additional_context?: string | null;
}

// ============================================================
// Roadmap Framework Models
// ============================================================

export interface Concept {
  concept_id: string;
  name: string;
  description: string;
  estimated_hours: number;
  prerequisites: string[];
  difficulty: 'easy' | 'medium' | 'hard';
  keywords: string[];
  content_status: 'pending' | 'generating' | 'completed' | 'failed';
  content_ref?: string | null;
  content_version: string;
  content_summary?: string | null;
  resources_status: 'pending' | 'generating' | 'completed' | 'failed';
  resources_id?: string | null;
  resources_count: number;
  quiz_status: 'pending' | 'generating' | 'completed' | 'failed';
  quiz_id?: string | null;
  quiz_questions_count: number;
}

export interface Module {
  module_id: string;
  name: string;
  description: string;
  concepts: Concept[];
}

export interface Stage {
  stage_id: string;
  name: string;
  description: string;
  order: number;
  modules: Module[];
}

export interface RoadmapFramework {
  roadmap_id: string;
  title: string;
  stages: Stage[];
  total_estimated_hours: number;
  recommended_completion_weeks: number;
}

// ============================================================
// Tutorial Models
// ============================================================

export interface TutorialSection {
  section_id: string;
  title: string;
  content: string;
  content_type: 'theory' | 'example' | 'exercise' | 'quiz';
  estimated_minutes: number;
}

export interface Tutorial {
  tutorial_id: string;
  concept_id: string;
  title: string;
  summary: string;
  sections: TutorialSection[];
  recommended_resources: Array<{ title: string; url: string; type: string }>;
  exercises: string[];
  estimated_completion_time: number;
  version: string;
  generated_at: string;
  storage_url?: string | null;
}

// ============================================================
// Resource Models
// ============================================================

export interface Resource {
  title: string;
  url: string;
  type: 'article' | 'video' | 'book' | 'course' | 'documentation' | 'tool';
  description: string;
  relevance_score: number;
}

export interface ResourceRecommendationOutput {
  id: string;
  concept_id: string;
  resources: Resource[];
  search_queries_used: string[];
  generated_at: string;
}

// ============================================================
// Quiz Models
// ============================================================

export interface QuizQuestion {
  question_id: string;
  question_type: 'single_choice' | 'multiple_choice' | 'true_false' | 'fill_blank';
  question: string;
  options: string[];
  correct_answer: number[];
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export interface QuizGenerationOutput {
  concept_id: string;
  quiz_id: string;
  questions: QuizQuestion[];
  total_questions: number;
  generated_at: string;
}

// ============================================================
// Modification Models
// ============================================================

export type ModificationType = 'tutorial' | 'resources' | 'quiz' | 'concept';

export interface SingleModificationIntent {
  modification_type: ModificationType;
  target_id: string;
  target_name: string;
  specific_requirements: string[];
  priority: 'high' | 'medium' | 'low';
}

export interface ModificationAnalysisOutput {
  intents: SingleModificationIntent[];
  overall_confidence: number;
  needs_clarification: boolean;
  clarification_questions: string[];
  analysis_reasoning: string;
}

export interface SingleModificationResult {
  modification_type: ModificationType;
  target_id: string;
  target_name: string;
  success: boolean;
  modification_summary: string;
  new_version?: number | null;
  error_message?: string | null;
}

export interface BatchModificationResult {
  results: SingleModificationResult[];
  overall_success: boolean;
  partial_success: boolean;
  summary: string;
}

// ============================================================
// API Response Models
// ============================================================

export interface TaskStatus {
  task_id: string;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  current_step?: string | null;
  progress?: number | null;
  error_message?: string | null;
  roadmap_id?: string | null;
}

export interface GenerateRoadmapResponse {
  task_id: string;
  status: string;
  message: string;
}
`;

  fs.writeFileSync(
    path.join(modelsDir, 'index.ts'),
    placeholderTypes,
    'utf-8'
  );

  // Create services placeholder
  const servicesDir = path.join(OUTPUT_DIR, 'services');
  if (!fs.existsSync(servicesDir)) {
    fs.mkdirSync(servicesDir, { recursive: true });
  }

  const servicesPlaceholder = `/**
 * Placeholder Services - Generated when backend is unavailable
 */

export class RoadmapService {
  // Placeholder - will be generated when backend is available
}
`;

  fs.writeFileSync(
    path.join(servicesDir, 'index.ts'),
    servicesPlaceholder,
    'utf-8'
  );

  // Create core directory with basic types
  const coreDir = path.join(OUTPUT_DIR, 'core');
  if (!fs.existsSync(coreDir)) {
    fs.mkdirSync(coreDir, { recursive: true });
  }

  const coreTypes = `/**
 * Core API Types
 */

export interface ApiError {
  status: number;
  statusText: string;
  body: unknown;
  url: string;
}

export interface ApiRequestOptions {
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  url: string;
  path?: Record<string, unknown>;
  query?: Record<string, unknown>;
  headers?: Record<string, string>;
  body?: unknown;
}

export interface ApiResult<T = unknown> {
  data: T;
  status: number;
  headers: Record<string, string>;
}
`;

  fs.writeFileSync(
    path.join(coreDir, 'ApiError.ts'),
    'export interface ApiError { status: number; statusText: string; body: unknown; url: string; }',
    'utf-8'
  );

  fs.writeFileSync(
    path.join(coreDir, 'ApiRequestOptions.ts'),
    coreTypes.split('export interface ApiRequestOptions')[1]?.split('export interface')[0] || 
    'export interface ApiRequestOptions { method: string; url: string; }',
    'utf-8'
  );

  fs.writeFileSync(
    path.join(coreDir, 'ApiResult.ts'),
    'export interface ApiResult<T = unknown> { data: T; status: number; }',
    'utf-8'
  );

  // Create main index file
  const indexContent = `/**
 * Generated Types (Placeholder)
 * 
 * These are placeholder types. Run \`npm run generate:types\` 
 * with the backend running to get full types.
 */

export * from './models';
export * from './core/ApiError';
export * from './core/ApiRequestOptions';
export * from './core/ApiResult';
`;

  fs.writeFileSync(
    path.join(OUTPUT_DIR, 'index.ts'),
    indexContent,
    'utf-8'
  );

  console.log('✅ Placeholder types generated successfully!');
}

// Run the script
generateTypes();

