"""make_edit_plan_feedback_id_optional

Revision ID: 354c6fbf7a16
Revises: 8a8c29457b8c
Create Date: 2026-01-14 01:10:21.331292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354c6fbf7a16'
down_revision: Union[str, None] = '8a8c29457b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edit_plan_records', 'feedback_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edit_plan_records', 'feedback_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###

