"""add_dimension_scores_and_suggestions_to_validation

Revision ID: 387eeb1a5122
Revises: ef6a7e5aabd5
Create Date: 2025-12-21 16:27:00.404139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '387eeb1a5122'
down_revision: Union[str, None] = 'ef6a7e5aabd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 只添加新字段到 structure_validation_records 表
    op.add_column('structure_validation_records', sa.Column('dimension_scores', sa.JSON(), nullable=True))
    op.add_column('structure_validation_records', sa.Column('improvement_suggestions', sa.JSON(), nullable=True))
    op.add_column('structure_validation_records', sa.Column('validation_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 回滚时删除这些字段
    op.drop_column('structure_validation_records', 'validation_summary')
    op.drop_column('structure_validation_records', 'improvement_suggestions')
    op.drop_column('structure_validation_records', 'dimension_scores')
    # ### end Alembic commands ###

