"""remove env and rate_limit_per_minute from tavily_api_keys

Revision ID: 38ef39810071
Revises: 20260115_remove_fkey
Create Date: 2026-01-16 21:47:57.298734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38ef39810071'
down_revision: Union[str, None] = '20260115_remove_fkey'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intent_analysis_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('uix_intent_roadmap_id'), 'intent_analysis_metadata', type_='unique')
    op.create_index('uix_intent_roadmap_id', 'intent_analysis_metadata', ['roadmap_id'], unique=True)
    op.alter_column('quiz_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resource_recommendation_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roadmap_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_roadmap_tasks_roadmap_id'), 'roadmap_tasks', ['roadmap_id'], unique=False)
    op.drop_column('tavily_api_keys', 'rate_limit_per_minute')
    op.drop_column('tavily_api_keys', 'env')
    op.alter_column('tech_stack_assessments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tutorial_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tutorial_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tech_stack_assessments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('tavily_api_keys', sa.Column('env', sa.VARCHAR(length=20), server_default=sa.text("'production'::character varying"), autoincrement=False, nullable=True))
    op.add_column('tavily_api_keys', sa.Column('rate_limit_per_minute', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_roadmap_tasks_roadmap_id'), table_name='roadmap_tasks')
    op.alter_column('roadmap_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resource_recommendation_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('quiz_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('uix_intent_roadmap_id', table_name='intent_analysis_metadata')
    op.create_unique_constraint(op.f('uix_intent_roadmap_id'), 'intent_analysis_metadata', ['roadmap_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('intent_analysis_metadata', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###

