"""add_soft_delete_to_roadmap_metadata

Revision ID: 46b11db29fd5
Revises: bb90a4da39fe
Create Date: 2025-12-10 23:34:24.213893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46b11db29fd5'
down_revision: Union[str, None] = 'bb90a4da39fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.alter_column('execution_logs', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('execution_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_execution_logs_created_at'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_trace_category'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_trace_level'), table_name='execution_logs')
    op.alter_column('intent_analysis_metadata', 'parsed_goal',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('intent_analysis_metadata', 'key_technologies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('intent_analysis_metadata', 'difficulty_profile',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('intent_analysis_metadata', 'time_constraint',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('intent_analysis_metadata', 'recommended_focus',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('intent_analysis_metadata', 'skill_gap_analysis',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('intent_analysis_metadata', 'personalized_suggestions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('intent_analysis_metadata', 'full_analysis_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('quiz_metadata', 'questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('resource_recommendation_metadata', 'resources',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('resource_recommendation_metadata', 'search_queries_used',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('roadmap_metadata', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('roadmap_metadata', sa.Column('deleted_by', sa.String(), nullable=True))
    op.drop_index(op.f('ix_tutorial_metadata_roadmap_concept_latest'), table_name='tutorial_metadata')
    op.alter_column('user_profiles', 'tech_stack',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('user_profiles', 'learning_style',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'learning_style',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('user_profiles', 'tech_stack',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.create_index(op.f('ix_tutorial_metadata_roadmap_concept_latest'), 'tutorial_metadata', ['roadmap_id', 'concept_id', 'is_latest'], unique=False)
    op.drop_column('roadmap_metadata', 'deleted_by')
    op.drop_column('roadmap_metadata', 'deleted_at')
    op.alter_column('resource_recommendation_metadata', 'search_queries_used',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('resource_recommendation_metadata', 'resources',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('quiz_metadata', 'questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('intent_analysis_metadata', 'full_analysis_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('intent_analysis_metadata', 'personalized_suggestions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('intent_analysis_metadata', 'skill_gap_analysis',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('intent_analysis_metadata', 'recommended_focus',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('intent_analysis_metadata', 'time_constraint',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('intent_analysis_metadata', 'difficulty_profile',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('intent_analysis_metadata', 'key_technologies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('intent_analysis_metadata', 'parsed_goal',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_execution_logs_trace_level'), 'execution_logs', ['task_id', 'level'], unique=False)
    op.create_index(op.f('ix_execution_logs_trace_category'), 'execution_logs', ['task_id', 'category'], unique=False)
    op.create_index(op.f('ix_execution_logs_created_at'), 'execution_logs', ['created_at'], unique=False)
    op.alter_column('execution_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('execution_logs', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    # ### end Alembic commands ###

