"""add_cascade_delete_to_task_foreign_keys

Revision ID: 6df605025673
Revises: 38ef39810071
Create Date: 2026-01-24 22:14:27.505770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df605025673'
down_revision: Union[str, None] = '38ef39810071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ✅ 移除旧的外键约束并添加带 CASCADE 的新约束
    
    # edit_plan_records 表
    op.drop_constraint('edit_plan_records_feedback_id_fkey', 'edit_plan_records', type_='foreignkey')
    op.drop_constraint('edit_plan_records_task_id_fkey', 'edit_plan_records', type_='foreignkey')
    op.create_foreign_key('edit_plan_records_feedback_id_fkey', 'edit_plan_records', 'human_review_feedbacks', ['feedback_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('edit_plan_records_task_id_fkey', 'edit_plan_records', 'roadmap_tasks', ['task_id'], ['task_id'], ondelete='CASCADE')
    
    # human_review_feedbacks 表
    op.drop_constraint('human_review_feedbacks_task_id_fkey', 'human_review_feedbacks', type_='foreignkey')
    op.create_foreign_key('human_review_feedbacks_task_id_fkey', 'human_review_feedbacks', 'roadmap_tasks', ['task_id'], ['task_id'], ondelete='CASCADE')
    
    # roadmap_edit_records 表
    op.drop_constraint('roadmap_edit_records_task_id_fkey', 'roadmap_edit_records', type_='foreignkey')
    op.create_foreign_key('roadmap_edit_records_task_id_fkey', 'roadmap_edit_records', 'roadmap_tasks', ['task_id'], ['task_id'], ondelete='CASCADE')
    
    # structure_validation_records 表
    op.drop_constraint('structure_validation_records_task_id_fkey', 'structure_validation_records', type_='foreignkey')
    op.create_foreign_key('structure_validation_records_task_id_fkey', 'structure_validation_records', 'roadmap_tasks', ['task_id'], ['task_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ✅ 回滚：移除带 CASCADE 的约束，恢复原来的外键约束
    
    # structure_validation_records 表
    op.drop_constraint('structure_validation_records_task_id_fkey', 'structure_validation_records', type_='foreignkey')
    op.create_foreign_key('structure_validation_records_task_id_fkey', 'structure_validation_records', 'roadmap_tasks', ['task_id'], ['task_id'])
    
    # roadmap_edit_records 表
    op.drop_constraint('roadmap_edit_records_task_id_fkey', 'roadmap_edit_records', type_='foreignkey')
    op.create_foreign_key('roadmap_edit_records_task_id_fkey', 'roadmap_edit_records', 'roadmap_tasks', ['task_id'], ['task_id'])
    
    # human_review_feedbacks 表
    op.drop_constraint('human_review_feedbacks_task_id_fkey', 'human_review_feedbacks', type_='foreignkey')
    op.create_foreign_key('human_review_feedbacks_task_id_fkey', 'human_review_feedbacks', 'roadmap_tasks', ['task_id'], ['task_id'])
    
    # edit_plan_records 表
    op.drop_constraint('edit_plan_records_task_id_fkey', 'edit_plan_records', type_='foreignkey')
    op.drop_constraint('edit_plan_records_feedback_id_fkey', 'edit_plan_records', type_='foreignkey')
    op.create_foreign_key('edit_plan_records_task_id_fkey', 'edit_plan_records', 'roadmap_tasks', ['task_id'], ['task_id'])
    op.create_foreign_key('edit_plan_records_feedback_id_fkey', 'edit_plan_records', 'human_review_feedbacks', ['feedback_id'], ['id'])
    # ### end Alembic commands ###

