"""add_concept_metadata_table

Revision ID: c0f1e2d3a4b5
Revises: ede0773860b9
Create Date: 2025-01-01 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'c0f1e2d3a4b5'
down_revision: Union[str, None] = 'ede0773860b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    创建 concept_metadata 表，用于追踪每个 Concept 的内容生成状态
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_metadata',
    sa.Column('concept_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='概念 ID（来自 framework_data）'),
    sa.Column('roadmap_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='关联的路线图 ID'),
    sa.Column('tutorial_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='pending', comment='Tutorial 生成状态: pending/generating/completed/failed'),
    sa.Column('tutorial_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Tutorial ID（UUID 格式）'),
    sa.Column('tutorial_completed_at', sa.DateTime(), nullable=True, comment='Tutorial 完成时间（北京时间）'),
    sa.Column('resources_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='pending', comment='Resources 生成状态: pending/generating/completed/failed'),
    sa.Column('resources_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Resources ID（UUID 格式）'),
    sa.Column('resources_completed_at', sa.DateTime(), nullable=True, comment='Resources 完成时间（北京时间）'),
    sa.Column('quiz_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='pending', comment='Quiz 生成状态: pending/generating/completed/failed'),
    sa.Column('quiz_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Quiz ID（UUID 格式）'),
    sa.Column('quiz_completed_at', sa.DateTime(), nullable=True, comment='Quiz 完成时间（北京时间）'),
    sa.Column('overall_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='pending', comment='整体状态: pending/generating/completed/partial_failed（三项全部完成才是 completed）'),
    sa.Column('all_content_completed_at', sa.DateTime(), nullable=True, comment='全部内容完成时间（北京时间）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间（北京时间）'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='最后更新时间（北京时间）'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap_metadata.roadmap_id'], ),
    sa.PrimaryKeyConstraint('concept_id')
    )
    
    # 创建索引以优化查询
    op.create_index(op.f('ix_concept_metadata_roadmap_id'), 'concept_metadata', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_concept_metadata_tutorial_status'), 'concept_metadata', ['tutorial_status'], unique=False)
    op.create_index(op.f('ix_concept_metadata_resources_status'), 'concept_metadata', ['resources_status'], unique=False)
    op.create_index(op.f('ix_concept_metadata_quiz_status'), 'concept_metadata', ['quiz_status'], unique=False)
    op.create_index(op.f('ix_concept_metadata_overall_status'), 'concept_metadata', ['overall_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    删除 concept_metadata 表
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concept_metadata_overall_status'), table_name='concept_metadata')
    op.drop_index(op.f('ix_concept_metadata_quiz_status'), table_name='concept_metadata')
    op.drop_index(op.f('ix_concept_metadata_resources_status'), table_name='concept_metadata')
    op.drop_index(op.f('ix_concept_metadata_tutorial_status'), table_name='concept_metadata')
    op.drop_index(op.f('ix_concept_metadata_roadmap_id'), table_name='concept_metadata')
    op.drop_table('concept_metadata')
    # ### end Alembic commands ###

