"""rename_trace_id_to_task_id

Revision ID: bb90a4da39fe
Revises: phase3_composite_idx
Create Date: 2025-12-07 11:52:38.294713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb90a4da39fe'
down_revision: Union[str, None] = 'phase3_composite_idx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop LangGraph checkpoint tables (not needed in application database)
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes', if_exists=True)
    op.drop_table('checkpoint_writes', if_exists=True)
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints', if_exists=True)
    op.drop_table('checkpoints', if_exists=True)
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs', if_exists=True)
    op.drop_table('checkpoint_blobs', if_exists=True)
    op.drop_table('checkpoint_migrations', if_exists=True)
    
    # Drop old indexes on trace_id
    op.drop_index('idx_execution_logs_trace_category_created', table_name='execution_logs')
    op.drop_index('idx_execution_logs_trace_level_created', table_name='execution_logs')
    op.drop_index('ix_execution_logs_trace_id', table_name='execution_logs')
    
    # Rename trace_id to task_id
    op.alter_column('execution_logs', 'trace_id', new_column_name='task_id')
    
    # Create new index on task_id
    op.create_index(op.f('ix_execution_logs_task_id'), 'execution_logs', ['task_id'], unique=False)
    # Drop redundant composite indexes (they were just created in previous migration but not optimal)
    op.drop_index('idx_quiz_metadata_roadmap_concept', table_name='quiz_metadata')
    op.drop_index('idx_resource_recommendation_roadmap_concept', table_name='resource_recommendation_metadata')
    op.drop_index('idx_roadmap_tasks_roadmap_status', table_name='roadmap_tasks')
    op.drop_index('idx_tutorial_metadata_roadmap_concept_latest', table_name='tutorial_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade: rename task_id back to trace_id"""
    # Drop new index on task_id
    op.drop_index(op.f('ix_execution_logs_task_id'), table_name='execution_logs')
    
    # Rename task_id back to trace_id
    op.alter_column('execution_logs', 'task_id', new_column_name='trace_id')
    
    # Recreate old indexes on trace_id
    op.create_index('ix_execution_logs_trace_id', 'execution_logs', ['trace_id'], unique=False)
    op.create_index('idx_execution_logs_trace_level_created', 'execution_logs', ['trace_id', 'level', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_execution_logs_trace_category_created', 'execution_logs', ['trace_id', 'category', sa.text('created_at DESC')], unique=False)
    
    # Recreate composite indexes
    op.create_index('idx_tutorial_metadata_roadmap_concept_latest', 'tutorial_metadata', ['roadmap_id', 'concept_id', 'is_latest'], unique=False)
    op.create_index('idx_roadmap_tasks_roadmap_status', 'roadmap_tasks', ['roadmap_id', 'status'], unique=False)
    op.create_index('idx_resource_recommendation_roadmap_concept', 'resource_recommendation_metadata', ['roadmap_id', 'concept_id'], unique=False)
    op.create_index('idx_quiz_metadata_roadmap_concept', 'quiz_metadata', ['roadmap_id', 'concept_id'], unique=False)

