"""Add tavily_api_keys table

Revision ID: ede0773860b9
Revises: 9a8f7b6c5d4e
Create Date: 2025-12-24 07:22:44.201927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ede0773860b9'
down_revision: Union[str, None] = '9a8f7b6c5d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tavily_api_keys',
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('plan_limit', sa.Integer(), nullable=False),
    sa.Column('remaining_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('api_key')
    )
    op.alter_column('edit_plan_records', 'feedback_summary',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('edit_plan_records', 'scope_analysis',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('edit_plan_records', 'intents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('edit_plan_records', 'preservation_requirements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('edit_plan_records', 'full_plan_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('edit_plan_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('human_review_feedbacks', 'roadmap_version_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('human_review_feedbacks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('human_review_feedbacks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('human_review_feedbacks', 'roadmap_version_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('edit_plan_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('edit_plan_records', 'full_plan_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('edit_plan_records', 'preservation_requirements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('edit_plan_records', 'intents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('edit_plan_records', 'scope_analysis',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('edit_plan_records', 'feedback_summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_table('tavily_api_keys')
    # ### end Alembic commands ###

